services:
  - type: web
    name: CMS_BLOG_LATEST
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn cms_backend.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: cms-blog-latest.onrender.com,.onrender.com
      - key: CORS_ALLOWED_ORIGINS
        value: https://cms-blog-frontend.vercel.app,https://cms-blog-latest.vercel.app
      - key: DATABASE_URL
        fromDatabase:
          name: cms_blog_db
          property: connectionString

  - type: pserv
    name: cms_blog_db
    env: postgres
    plan: free

databases:
  - name: cms-blog-db
    databaseName: cms_blog
    user: cms_blog_user
    plan: free 